-- 数据库初始化脚本

-- 创建数据库
CREATE DATABASE babaSport;

USE babaSport;

CREATE TABLE `test_db` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `birthday` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET = utf8 COMMENT = '测试表';

CREATE TABLE `bbs_brand` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(40) NOT NULL COMMENT '名称',
  `description` VARCHAR(80) DEFAULT NULL COMMENT '描述',
  `img_url` VARCHAR(80) DEFAULT NULL COMMENT '图片Url',
  `web_site` VARCHAR(80) DEFAULT NULL COMMENT '品牌网址',
  `sort` INT(10) DEFAULT NULL COMMENT '排序:最大排最前',
  `is_display` TINYINT(1) DEFAULT NULL COMMENT '是否可见 1:可见0:不可见',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT=83 DEFAULT CHARSET =utf8 COMMENT = '品牌';


